// ignore_for_file: avoid_print

// ---------------------------------------------------------------------------
// Phase 6.2 — Turn Analysis — Unit Tests
// ---------------------------------------------------------------------------
//
// All tests use deterministic synthetic GPS tracks.
// No physical device, GPS, internet, or database required.
//
// ## Track generation strategy
//
// Points are generated by advancing in a bearing direction by a fixed
// step distance using the _advance helper (inverse haversine).  This
// produces realistic coordinate sequences along a known heading.
//
// The window-size default is 5, minTurnAngleDeg = 35°,
// debounceDistanceM = 30 m.  Test tracks use 20 m steps so each window
// covers ~80 m — well above the movement and debounce thresholds.
//
// ## Sign convention (verified explicitly)
//
//   headingChangeDegrees: positive → RIGHT, negative → LEFT
//   angleDeg on TurnEvent follows the same convention.

import 'dart:math' as math;

import 'package:flutter_test/flutter_test.dart';

import 'package:triprank_project/features/analytics/models/turn_analysis.dart';
import 'package:triprank_project/features/analytics/models/turn_event.dart';
import 'package:triprank_project/features/analytics/services/turn_detector.dart';
import 'package:triprank_project/features/analytics/services/gps_math_utils.dart';
import 'package:triprank_project/features/trips/models/track_point_record.dart';

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

final _t0 = DateTime.utc(2024, 1, 1, 9, 0, 0);
DateTime _ts(int s) => _t0.add(Duration(seconds: s));

/// Earth radius in metres (WGS 84 mean).
const _earthR = 6371000.0;

/// Advance a (lat, lng) point by [distM] metres along [bearingDeg] degrees.
///
/// Uses the inverse haversine formula.
({double lat, double lng}) _advance(
  double lat,
  double lng,
  double bearingDeg,
  double distM,
) {
  final d = distM / _earthR;
  final b = bearingDeg * math.pi / 180;
  final lat1 = lat * math.pi / 180;
  final lng1 = lng * math.pi / 180;

  final lat2 = math.asin(
    math.sin(lat1) * math.cos(d) +
        math.cos(lat1) * math.sin(d) * math.cos(b),
  );
  final lng2 = lng1 +
      math.atan2(
        math.sin(b) * math.sin(d) * math.cos(lat1),
        math.cos(d) - math.sin(lat1) * math.sin(lat2),
      );

  return (lat: lat2 * 180 / math.pi, lng: lng2 * 180 / math.pi);
}

/// Builds a straight GPS track starting at (lat, lng), heading [bearingDeg],
/// with [count] points spaced [stepM] metres apart.
List<TrackPointRecord> _straight({
  double lat = 51.5,
  double lng = -0.1,
  double bearingDeg = 0, // north
  int count = 10,
  double stepM = 20,
  double? speedKmh,
}) {
  final pts = <TrackPointRecord>[];
  var cur = (lat: lat, lng: lng);
  for (var i = 0; i < count; i++) {
    pts.add(TrackPointRecord(
      id: 'p${i + 1}',
      tripId: 'trip-1',
      timestamp: _ts(i * 2),
      latitude: cur.lat,
      longitude: cur.lng,
      speedKmh: speedKmh,
    ));
    cur = _advance(cur.lat, cur.lng, bearingDeg, stepM);
  }
  return pts;
}

/// Builds a track that goes straight for [straightCount] points, then turns
/// by [turnDeg] degrees (positive = right, negative = left), then continues
/// straight for [afterCount] points.
List<TrackPointRecord> _withTurn({
  double lat = 51.5,
  double lng = -0.1,
  double initialBearingDeg = 0,
  int straightCount = 8,
  double turnDeg = 90, // positive = right, negative = left
  int afterCount = 8,
  double stepM = 20,
}) {
  final pts = <TrackPointRecord>[];
  var cur = (lat: lat, lng: lng);
  var t = 0;

  // Straight section
  for (var i = 0; i < straightCount; i++) {
    pts.add(TrackPointRecord(
      id: 'p${pts.length + 1}',
      tripId: 'trip-1',
      timestamp: _ts(t),
      latitude: cur.lat,
      longitude: cur.lng,
    ));
    cur = _advance(cur.lat, cur.lng, initialBearingDeg, stepM);
    t += 2;
  }

  // The turn point (midpoint of turn)
  pts.add(TrackPointRecord(
    id: 'p${pts.length + 1}',
    tripId: 'trip-1',
    timestamp: _ts(t),
    latitude: cur.lat,
    longitude: cur.lng,
  ));
  t += 2;

  // After-turn section
  final newBearing = (initialBearingDeg + turnDeg + 360) % 360;
  for (var i = 0; i < afterCount; i++) {
    cur = _advance(cur.lat, cur.lng, newBearing, stepM);
    pts.add(TrackPointRecord(
      id: 'p${pts.length + 1}',
      tripId: 'trip-1',
      timestamp: _ts(t),
      latitude: cur.lat,
      longitude: cur.lng,
    ));
    t += 2;
  }

  return pts;
}

const _detector = TurnDetector();

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

void main() {
  // ──────────────────────────────────────────────────────────────────────────
  // Group 1: Straight roads (expect 0 turns)
  // ──────────────────────────────────────────────────────────────────────────
  group('Straight road', () {
    test('Straight north road produces 0 turns', () {
      final pts = _straight(bearingDeg: 0, count: 20);
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0));
      expect(result.leftTurns, equals(0));
      expect(result.rightTurns, equals(0));
    });

    test('Straight east road produces 0 turns', () {
      final pts = _straight(bearingDeg: 90, count: 20);
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0));
    });

    test('Straight road with minor GPS jitter produces 0 turns', () {
      // Add ±0.00002° jitter (~2 m) to an otherwise straight north track.
      final rng = math.Random(42);
      final pts = _straight(bearingDeg: 0, count: 20).map((p) {
        final jitterLat = (rng.nextDouble() - 0.5) * 0.00004; // ±~4 m
        final jitterLng = (rng.nextDouble() - 0.5) * 0.00004;
        return TrackPointRecord(
          id: p.id,
          tripId: p.tripId,
          timestamp: p.timestamp,
          latitude: p.latitude + jitterLat,
          longitude: p.longitude + jitterLng,
        );
      }).toList();
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0),
          reason: 'Small GPS jitter on a straight road must not generate turns');
    });

    test('Straight road with stationary points produces 0 turns', () {
      // Insert duplicate points (vehicle stopped).
      final pts = <TrackPointRecord>[];
      var cur = (lat: 51.5, lng: -0.1);
      for (var i = 0; i < 6; i++) {
        pts.add(TrackPointRecord(
          id: 'p${pts.length + 1}',
          tripId: 'trip-1',
          timestamp: _ts(i * 2),
          latitude: cur.lat,
          longitude: cur.lng,
        ));
        // Every 3rd point is stationary (same position)
        if (i % 3 != 2) {
          cur = _advance(cur.lat, cur.lng, 0, 20);
        }
      }
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 2: Left turn
  // ──────────────────────────────────────────────────────────────────────────
  group('Left turn', () {
    test('Clear 90° left turn produces exactly 1 left turn', () {
      final pts = _withTurn(
        initialBearingDeg: 0, // heading north
        turnDeg: -90,         // turn left → heading west
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.leftTurns, equals(1),
          reason: 'Expected 1 left turn');
      expect(result.rightTurns, equals(0));
      expect(result.uTurns, equals(0));
    });

    test('Left turn event has negative angleDeg', () {
      final pts = _withTurn(
        initialBearingDeg: 90,
        turnDeg: -90,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.leftTurns, equals(1));
      final turn = result.turns.first;
      expect(turn.direction, equals(TurnDirection.left));
      expect(turn.angleDeg, lessThan(0),
          reason: 'Left turn must have negative angleDeg');
    });

    test('45° left turn is detected (above threshold)', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: -45,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.leftTurns, greaterThanOrEqualTo(1));
      expect(result.rightTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 3: Right turn
  // ──────────────────────────────────────────────────────────────────────────
  group('Right turn', () {
    test('Clear 90° right turn produces exactly 1 right turn', () {
      final pts = _withTurn(
        initialBearingDeg: 0, // heading north
        turnDeg: 90,          // turn right → heading east
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.rightTurns, equals(1),
          reason: 'Expected 1 right turn');
      expect(result.leftTurns, equals(0));
      expect(result.uTurns, equals(0));
    });

    test('Right turn event has positive angleDeg', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 90,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.rightTurns, equals(1));
      final turn = result.turns.first;
      expect(turn.direction, equals(TurnDirection.right));
      expect(turn.angleDeg, greaterThan(0),
          reason: 'Right turn must have positive angleDeg');
    });

    test('45° right turn is detected (above threshold)', () {
      final pts = _withTurn(
        initialBearingDeg: 90,
        turnDeg: 45,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.rightTurns, greaterThanOrEqualTo(1));
      expect(result.leftTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 4: Multiple turns
  // ──────────────────────────────────────────────────────────────────────────
  group('Multiple turns', () {
    test('Left then right: straight→left→straight→right produces 1L 1R', () {
      // Build: 8 north → left 90° → 8 west → right 90° → 8 north
      final seg1 = _straight(lat: 51.5, lng: -0.1, bearingDeg: 0, count: 8);
      // After seg1, position is 8*20=160m north
      final seg1End = seg1.last;

      final turn1 = _withTurn(
        lat: seg1End.latitude,
        lng: seg1End.longitude,
        initialBearingDeg: 0,
        turnDeg: -90,
        straightCount: 0,
        afterCount: 10,
      );
      final afterLeft = turn1.last;

      final turn2 = _withTurn(
        lat: afterLeft.latitude,
        lng: afterLeft.longitude,
        initialBearingDeg: 270, // heading west
        turnDeg: 90,            // right → heading north
        straightCount: 0,
        afterCount: 8,
      );

      // Merge, renumber IDs, adjust timestamps
      final allPts = <TrackPointRecord>[];
      var t = 0;
      for (final src in [seg1, turn1, turn2]) {
        for (final p in src) {
          allPts.add(TrackPointRecord(
            id: 'p${allPts.length + 1}',
            tripId: 'trip-1',
            timestamp: _ts(t),
            latitude: p.latitude,
            longitude: p.longitude,
          ));
          t += 2;
        }
      }

      final result = _detector.detectTurns(allPts);
      expect(result.leftTurns, equals(1),
          reason: 'Expected exactly 1 left turn');
      expect(result.rightTurns, equals(1),
          reason: 'Expected exactly 1 right turn');
    });

    test('Two right turns produce 2 right turns, 0 left turns', () {
      final seg1 = _straight(lat: 51.5, lng: -0.1, bearingDeg: 0, count: 8);
      final seg1End = seg1.last;

      final turn1 = _withTurn(
        lat: seg1End.latitude,
        lng: seg1End.longitude,
        initialBearingDeg: 0,
        turnDeg: 90,
        straightCount: 0,
        afterCount: 10,
      );
      final afterRight1 = turn1.last;

      final turn2 = _withTurn(
        lat: afterRight1.latitude,
        lng: afterRight1.longitude,
        initialBearingDeg: 90,
        turnDeg: 90,
        straightCount: 0,
        afterCount: 8,
      );

      final allPts = <TrackPointRecord>[];
      var t = 0;
      for (final src in [seg1, turn1, turn2]) {
        for (final p in src) {
          allPts.add(TrackPointRecord(
            id: 'p${allPts.length + 1}',
            tripId: 'trip-1',
            timestamp: _ts(t),
            latitude: p.latitude,
            longitude: p.longitude,
          ));
          t += 2;
        }
      }

      final result = _detector.detectTurns(allPts);
      expect(result.rightTurns, equals(2));
      expect(result.leftTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 5: Gentle curve (expect 0 turns with default threshold)
  // ──────────────────────────────────────────────────────────────────────────
  group('Gentle curve', () {
    test('20° gradual curve does not produce a turn (below threshold)', () {
      // Spread 20° change across 20 points (1° per step)
      final pts = <TrackPointRecord>[];
      var cur = (lat: 51.5, lng: -0.1);
      var bearing = 0.0;
      for (var i = 0; i < 20; i++) {
        pts.add(TrackPointRecord(
          id: 'p${i + 1}',
          tripId: 'trip-1',
          timestamp: _ts(i * 2),
          latitude: cur.lat,
          longitude: cur.lng,
        ));
        bearing += 1.0; // 1° per step
        cur = _advance(cur.lat, cur.lng, bearing, 20);
      }
      final result = _detector.detectTurns(pts);
      // A 20° total change is below minTurnAngleDeg=35°, so 0 turns expected.
      expect(result.totalTurns, equals(0),
          reason: '20° gentle curve must not produce a turn event');
    });

    test('25° gradual curve does not produce a turn (just below threshold)',
        () {
      final pts = <TrackPointRecord>[];
      var cur = (lat: 51.5, lng: -0.1);
      var bearing = 0.0;
      for (var i = 0; i < 25; i++) {
        pts.add(TrackPointRecord(
          id: 'p${i + 1}',
          tripId: 'trip-1',
          timestamp: _ts(i * 2),
          latitude: cur.lat,
          longitude: cur.lng,
        ));
        bearing += 1.0;
        cur = _advance(cur.lat, cur.lng, bearing, 20);
      }
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 6: U-turn
  // ──────────────────────────────────────────────────────────────────────────
  group('U-turn', () {
    test('180° reversal is classified as uTurn, not left or right', () {
      // Use larger step and more points to ensure window movement threshold met.
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 180,
        straightCount: 10,
        afterCount: 10,
        stepM: 25,
      );
      final result = _detector.detectTurns(pts);
      // Must have at least one uTurn
      expect(result.uTurns, greaterThanOrEqualTo(1));
      // U-turns must NOT be counted in left or right
      expect(result.leftTurns, equals(0));
      expect(result.rightTurns, equals(0));
    });

    test('160° reversal is classified as uTurn (above uTurnThresholdDeg)', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: -160,
        straightCount: 10,
        afterCount: 10,
        stepM: 25,
      );
      final result = _detector.detectTurns(pts);
      expect(result.uTurns, greaterThanOrEqualTo(1));
      expect(result.leftTurns, equals(0));
      expect(result.rightTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 7: GPS noise resistance
  // ──────────────────────────────────────────────────────────────────────────
  group('GPS noise', () {
    test('Stationary GPS cluster (all same point) produces 0 turns', () {
      final pts = List.generate(
        15,
        (i) => TrackPointRecord(
          id: 'p${i + 1}',
          tripId: 'trip-1',
          timestamp: _ts(i),
          latitude: 51.5,
          longitude: -0.1,
        ),
      );
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0));
    });

    test('Very small movements (1 m steps) produce 0 false turns', () {
      final pts = _straight(stepM: 1, count: 50, bearingDeg: 45);
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0),
          reason: '1 m steps fall below minMovementM, no turns expected');
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 8: Missing data (must not crash)
  // ──────────────────────────────────────────────────────────────────────────
  group('Missing data', () {
    test('Null speed does not crash and does not prevent turn detection', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 90,
        straightCount: 8,
        afterCount: 8,
      );
      // All points have null speed (default in _withTurn)
      expect(() => _detector.detectTurns(pts), returnsNormally);
      final result = _detector.detectTurns(pts);
      expect(result.rightTurns, equals(1));
    });

    test('Null heading does not crash', () {
      final pts = _straight(count: 15); // no headingDegrees
      expect(() => _detector.detectTurns(pts), returnsNormally);
    });

    test('Duplicate timestamps do not crash', () {
      final t = _ts(0);
      final pts = List.generate(
        10,
        (i) => TrackPointRecord(
          id: 'p${i + 1}',
          tripId: 'trip-1',
          timestamp: t, // all same
          latitude: 51.5 + i * 0.001,
          longitude: -0.1,
        ),
      );
      expect(() => _detector.detectTurns(pts), returnsNormally);
    });

    test('Duplicate coordinates do not crash', () {
      final pts = List.generate(
        10,
        (i) => TrackPointRecord(
          id: 'p${i + 1}',
          tripId: 'trip-1',
          timestamp: _ts(i),
          latitude: 51.5,
          longitude: -0.1,
        ),
      );
      expect(() => _detector.detectTurns(pts), returnsNormally);
    });

    test('Short track (< windowSize) returns empty TurnAnalysis', () {
      final pts = _straight(count: 3); // windowSize default = 5
      final result = _detector.detectTurns(pts);
      expect(result, isA<TurnAnalysis>());
      expect(result.totalTurns, equals(0));
    });

    test('Empty track returns empty TurnAnalysis', () {
      final result = _detector.detectTurns([]);
      expect(result, isA<TurnAnalysis>());
      expect(result.totalTurns, equals(0));
    });

    test('Single point returns empty TurnAnalysis', () {
      final pts = [
        TrackPointRecord(
          id: 'p1',
          tripId: 'trip-1',
          timestamp: _ts(0),
          latitude: 51.5,
          longitude: -0.1,
        ),
      ];
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 9: Heading wraparound (0°/360° boundary)
  // ──────────────────────────────────────────────────────────────────────────
  group('Heading wraparound', () {
    test('355° → 5° change is treated as +10° right, not −350° left', () {
      final change = GpsMathUtils.headingChangeDegrees(355, 5);
      expect(change, isNotNull);
      expect(change!, closeTo(10, 0.001));
    });

    test('5° → 355° change is treated as −10° left, not +350° right', () {
      final change = GpsMathUtils.headingChangeDegrees(5, 355);
      expect(change, isNotNull);
      expect(change!, closeTo(-10, 0.001));
    });

    test('Track crossing 360° boundary is handled correctly', () {
      // Build a track heading ~355° (just west of north) then turning to 45°.
      // This crosses the 0°/360° boundary.
      final pts = _withTurn(
        initialBearingDeg: 355,
        turnDeg: 50, // 355 + 50 = 405 → 45° heading
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      // A 50° right turn should be detected
      expect(result.rightTurns, equals(1));
      expect(result.leftTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 10: Threshold boundary tests
  // ──────────────────────────────────────────────────────────────────────────
  group('Threshold boundary', () {
    test('Angle just below threshold (34°) is NOT classified as a turn', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 34, // just below 35° threshold
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, equals(0),
          reason: '34° is below the 35° threshold and must not produce a turn');
    });

    test('Angle just above threshold (36°) IS classified as a turn', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 36, // just above 35° threshold
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, greaterThanOrEqualTo(1),
          reason: '36° is above the 35° threshold and must produce a turn');
    });

    test('Angle just below uTurn threshold (149°) is classified as left/right',
        () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: -149,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      // Should be a left or uTurn but NOT classified as the opposite
      final allTurns = result.turns;
      for (final t in allTurns) {
        expect(t.direction, isNot(equals(TurnDirection.right)));
      }
    });

    test('Angle at uTurn threshold (150°) is classified as uTurn', () {
      // Use 155° rather than exactly 150° to avoid floating-point rounding
      // at the exact boundary.  The intent of the test is to verify that
      // angles at or above uTurnThresholdDeg are classified as uTurn, not
      // left or right — 155° is safely above 150° and reliably rounds up.
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 155,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.totalTurns, greaterThanOrEqualTo(1));
      expect(result.uTurns, greaterThanOrEqualTo(1));
      expect(result.leftTurns, equals(0));
      expect(result.rightTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 11: TurnAnalysis model tests
  // ──────────────────────────────────────────────────────────────────────────
  group('TurnAnalysis model', () {
    test('empty() factory produces zero counts', () {
      final ta = TurnAnalysis.empty();
      expect(ta.turns, isEmpty);
      expect(ta.leftTurns, equals(0));
      expect(ta.rightTurns, equals(0));
      expect(ta.uTurns, equals(0));
      expect(ta.totalTurns, equals(0));
      expect(ta.isEmpty, isTrue);
    });

    test('U-turns are not included in leftTurns or rightTurns', () {
      final events = [
        TurnEvent(
          direction: TurnDirection.left,
          timestamp: _ts(0),
          latitude: 51.5,
          longitude: -0.1,
          angleDeg: -90,
          entryBearingDeg: 0,
          exitBearingDeg: 270,
        ),
        TurnEvent(
          direction: TurnDirection.uTurn,
          timestamp: _ts(10),
          latitude: 51.5,
          longitude: -0.1,
          angleDeg: 170,
          entryBearingDeg: 0,
          exitBearingDeg: 170,
        ),
        TurnEvent(
          direction: TurnDirection.right,
          timestamp: _ts(20),
          latitude: 51.5,
          longitude: -0.1,
          angleDeg: 90,
          entryBearingDeg: 270,
          exitBearingDeg: 0,
        ),
      ];
      final ta = TurnAnalysis(turns: events);
      expect(ta.leftTurns, equals(1));
      expect(ta.rightTurns, equals(1));
      expect(ta.uTurns, equals(1));
      expect(ta.totalTurns, equals(3));
    });

    test('TurnEvent.absAngleDeg is always positive', () {
      final left = TurnEvent(
        direction: TurnDirection.left,
        timestamp: _ts(0),
        latitude: 51.5,
        longitude: -0.1,
        angleDeg: -90,
        entryBearingDeg: 0,
        exitBearingDeg: 270,
      );
      expect(left.absAngleDeg, equals(90));
      expect(left.isLeft, isTrue);
      expect(left.isRight, isFalse);
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 12: DrivingAnalyticsService integration
  // ──────────────────────────────────────────────────────────────────────────
  group('DrivingAnalyticsService integration', () {
    test('TurnAnalysis is non-null even for empty track', () {
      // This is tested via DrivingAnalytics.empty which is used internally
      final ta = TurnAnalysis.empty();
      expect(ta, isA<TurnAnalysis>());
      expect(ta.leftTurns, equals(0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 13: TurnDetectorConfig
  // ──────────────────────────────────────────────────────────────────────────
  group('TurnDetectorConfig', () {
    test('Custom config with higher threshold suppresses borderline turns', () {
      // Use a 60° threshold — a 45° turn should be ignored.
      final detector = TurnDetector(
        config: const TurnDetectorConfig(minTurnAngleDeg: 60),
      );
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 45,
        straightCount: 8,
        afterCount: 8,
      );
      final result = detector.detectTurns(pts);
      expect(result.totalTurns, equals(0),
          reason: '45° < 60° custom threshold, should not detect a turn');
    });

    test('Custom config with lower threshold catches more turns', () {
      // Use a 20° threshold — a 30° turn should now be detected.
      final detector = TurnDetector(
        config: const TurnDetectorConfig(
          minTurnAngleDeg: 20,
          debounceDistanceM: 10,
        ),
      );
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 30,
        straightCount: 8,
        afterCount: 8,
      );
      final result = detector.detectTurns(pts);
      expect(result.totalTurns, greaterThanOrEqualTo(1),
          reason: '30° > 20° custom threshold, should detect a turn');
    });

    test('Default config constants are correct', () {
      const cfg = TurnDetectorConfig();
      expect(cfg.windowSize, equals(TurnDetectorConfig.kDefaultWindowSize));
      expect(cfg.minTurnAngleDeg,
          equals(TurnDetectorConfig.kDefaultMinTurnAngleDeg));
      expect(cfg.uTurnThresholdDeg,
          equals(TurnDetectorConfig.kDefaultUTurnThresholdDeg));
      expect(cfg.minMovementM,
          equals(TurnDetectorConfig.kDefaultMinMovementM));
      expect(cfg.debounceDistanceM,
          equals(TurnDetectorConfig.kDefaultDebounceDistanceM));
      // Verify documented defaults explicitly
      expect(cfg.windowSize, equals(5));
      expect(cfg.minTurnAngleDeg, equals(35.0));
      expect(cfg.uTurnThresholdDeg, equals(150.0));
      expect(cfg.minMovementM, equals(10.0));
      expect(cfg.debounceDistanceM, equals(50.0));
    });
  });

  // ──────────────────────────────────────────────────────────────────────────
  // Group 14: Turn location and timestamp
  // ──────────────────────────────────────────────────────────────────────────
  group('Turn location and timestamp', () {
    test('Turn location is a valid GPS coordinate', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 90,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.rightTurns, equals(1));
      final t = result.turns.first;
      expect(t.latitude, greaterThan(-90));
      expect(t.latitude, lessThan(90));
      expect(t.longitude, greaterThan(-180));
      expect(t.longitude, lessThan(180));
    });

    test('Turn timestamp is within the track time range', () {
      final pts = _withTurn(
        initialBearingDeg: 0,
        turnDeg: 90,
        straightCount: 8,
        afterCount: 8,
      );
      final result = _detector.detectTurns(pts);
      expect(result.rightTurns, equals(1));
      final t = result.turns.first;
      expect(
          t.timestamp.isAfter(pts.first.timestamp) ||
              t.timestamp == pts.first.timestamp,
          isTrue);
      expect(
          t.timestamp.isBefore(pts.last.timestamp) ||
              t.timestamp == pts.last.timestamp,
          isTrue);
    });
  });
}
